// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoGlgN8iu8jhJed7GmLm686iQW3w19kXk',
    appId: '1:939510992335:web:49a03857f798a532f2d6ba',
    messagingSenderId: '939510992335',
    projectId: 'try-catch-all',
    authDomain: 'try-catch-all.firebaseapp.com',
    storageBucket: 'try-catch-all.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBrV8RokHHCPxI7m1LYYGJKzraFAgReXw',
    appId: '1:939510992335:android:a89bb858813e0ebff2d6ba',
    messagingSenderId: '939510992335',
    projectId: 'try-catch-all',
    storageBucket: 'try-catch-all.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcu6zbVd9rPJE9w84f_3xVH7b4Vs6VO4E',
    appId: '1:939510992335:ios:08d3c3d1d9f4c12df2d6ba',
    messagingSenderId: '939510992335',
    projectId: 'try-catch-all',
    storageBucket: 'try-catch-all.firebasestorage.app',
    iosClientId: '939510992335-4g2h7qsr52465vm0ar52qifbhin6aofe.apps.googleusercontent.com',
    iosBundleId: 'com.example.catchAllApp',
  );

}