// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfdXoWih2sZzotf4rkakXzLcuLASmUmvU',
    appId: '1:375122364789:web:b371da0972e8d061ceab3c',
    messagingSenderId: '375122364789',
    projectId: 'catch-all-app',
    authDomain: 'catch-all-app.firebaseapp.com',
    storageBucket: 'catch-all-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOp62zT-BMWUVfmgJQQTZilxD8ULmudxQ',
    appId: '1:375122364789:android:a303f1e42ed99fdaceab3c',
    messagingSenderId: '375122364789',
    projectId: 'catch-all-app',
    storageBucket: 'catch-all-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuHHqzxkpWNzKhqf9waORTKrD7e3OuAp0',
    appId: '1:375122364789:ios:ae47f39ddf329947ceab3c',
    messagingSenderId: '375122364789',
    projectId: 'catch-all-app',
    storageBucket: 'catch-all-app.firebasestorage.app',
    iosBundleId: 'com.example.catchPokeApp',
  );
}
